default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        stages:
          - commit
      - id: end-of-file-fixer
        exclude: \.svg$
        stages:
          - commit

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
        stages:
          - commit

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: local
    hooks:
      - id: style
        name: style
        entry: flakeheaven lint
        exclude: /migrations/
        language: system
        types: [ python ]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        entry: mypy
        pass_filenames: true
        args: [ --follow-imports=silent ]  # workaround to import custom stubs correctly
        exclude: /migrations/
        additional_dependencies:
          - types-croniter==1.3.0
          - types-dateparser==1.1.4
          - types-freezegun==1.1.10
          - types-python-dateutil==2.8.18
          - types-pytz==2022.1.1
          - types-requests==2.28.1
          - types-bleach==5.0.3
          - types-PyYAML==6.0.9
