# Generated by Django 4.2.2 on 2024-06-16 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн"),
                            ("on_receipt_card", "Картой при получении"),
                            ("on_receipt_cash", "Наличными при получении"),
                            ("koronapay", "Золотая корона"),
                            ("legal", "Договор для юридических лиц"),
                        ],
                        help_text="Название варианта оплаты",
                        max_length=512,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант оплаты",
                "verbose_name_plural": "Варианты оплаты",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Название",
                        max_length=128,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Номер телефона",
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("\\A[+7,8]\\d{11,12}")
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Страна", null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Город", null=True, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, help_text="Улица", null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True, help_text="Дом", null=True, verbose_name="Дом"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Почтовый индекс",
                        null=True,
                        verbose_name="Почтовый индекс",
                    ),
                ),
                (
                    "geo_lat",
                    models.CharField(
                        blank=True, help_text="Широта", null=True, verbose_name="Широта"
                    ),
                ),
                (
                    "geo_lon",
                    models.CharField(
                        blank=True,
                        help_text="Долгота",
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес поставщика",
                "verbose_name_plural": "Адрес поставщика",
            },
        ),
    ]
