# Generated by Django 4.2.2 on 2023-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_is_dealer_user_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_dealer",
            field=models.BooleanField(
                default=False,
                help_text="Является ли пользователь дилером",
                verbose_name="Является дилером",
            ),
        ),
    ]
