# Generated by Django 4.2.2 on 2023-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_is_dealer"),
    ]

    operations = [
        migrations.AddField(
            model_name="smskey",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
