# Generated by Django 4.2.2 on 2023-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_smskey_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="password"
            ),
        ),
    ]
