# Generated by Django 4.2.2 on 2023-11-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор контрагента сервиса Мой Склад",
                null=True,
                verbose_name="Идентификатор контрагента сервиса Мой Склад",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Указывает, активирована ли учетная запись пользователя",
                verbose_name="Пользователь активен (не забанен)",
            ),
        ),
    ]
