# Generated by Django 4.2.2 on 2024-01-10 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_agent_id_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="update_username",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона",
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}"
                    )
                ],
                verbose_name="Новый номер телефона",
            ),
        ),
    ]
